<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product = new App\Product();
        $product->name = 'برتقال';
        $product->description = 'فاكهة لذيذة جميلة';
        $product->resource = 'المتعارف علية';
        $product->calories = '230';
        $product->calories_from_fat = '23';
        $product->total_fat = '23';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '23';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '14';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '400';
        $product->save();

        $product = new App\Product();
        $product->name = 'ليمون';
        $product->description = 'فاكهة لذيذة حلوة';
        $product->resource = 'الشارع العام';
        $product->calories = '288';
        $product->calories_from_fat = '23';
        $product->total_fat = '23';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '23';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '14';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '400';
        $product->save();

        $product = new App\Product();
        $product->name = 'حليب السعودية';
        $product->description = 'حليب الطيبين';
        $product->resource = 'الشارع العام';
        $product->calories = '543';
        $product->calories_from_fat = '23';
        $product->total_fat = '23';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '23';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '14';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '400';
        $product->save();

        $product = new App\Product();
        $product->name = 'حليب الوم';
        $product->description = 'حليب ما ادري';
        $product->resource = 'مهب الشارع العام';
        $product->calories = '100';
        $product->calories_from_fat = '23';
        $product->total_fat = '23';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '23';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '14';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '400';
        $product->save();

        $product = new App\Product();
        $product->name = 'حليب نادك';
        $product->description = 'حليب المتوسطين';
        $product->resource = 'السوبر ماركيت ';
        $product->calories = '333';
        $product->calories_from_fat = '23';
        $product->total_fat = '23';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '23';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '14';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '400';
        $product->save();

        $product = new App\Product();
        $product->name = 'حليب المراعي';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '900';
        $product->calories_from_fat = '23';
        $product->total_fat = '23';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '23';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '14';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '400';
        $product->save();

        $product = new App\Product();
        $product->name = 'بيبسي';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '145';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '43';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '44';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '400';
        $product->save();

        $product = new App\Product();
        $product->name = 'خبز فونتي';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '21';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();

        $product = new App\Product();
        $product->name = 'خبز لوزين';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '200';
        $product->calories_from_fat = '23';
        $product->total_fat = '43';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '100';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '22';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '120';
        $product->save();


        $product = new App\Product();
        $product->name = 'خبز الصالحي';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'بطيخ';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '122';
        $product->calories_from_fat = '23';
        $product->total_fat = '88';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '11';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '43';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'حبحر';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'طماطم';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '77';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'روبيان';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '333';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'حليب المراعي قليل الدسم';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '777';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'رز ام احمد';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '1300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'رز أم عبدالله';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '1500';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'شوربة ماجي';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '4444';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'شاورما الطيبين';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '22';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'ليس بمنتج';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '432';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'مرقوق';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '234';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'شابووره';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '666';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'صامولي';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '32';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '100';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'سفن اب';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'ميرندا';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


        $product = new App\Product();
        $product->name = 'شوربة مهب ماجي';
        $product->description = 'حليب الجديدن';
        $product->resource = 'الشارع العام';
        $product->calories = '300';
        $product->calories_from_fat = '23';
        $product->total_fat = '50';
        $product->trans_fat = '10';
        $product->saturated_fat = '.05';
        $product->cholesterol = '22';
        $product->sodium = '43';
        $product->total_carbohydrate = '55';
        $product->dietary_fiber = '24';
        $product->sugars = '24';
        $product->protein = '300';
        $product->vitamin_A = '1';
        $product->vitamin_C = '5';
        $product->calcium = '6';
        $product->iron = '7';
        $product->vitamin_d = '43';
        $product->potassium = '2';
        $product->serving_size = '100';
        $product->save();


    }
}
